default: &default
  adapter:  postgresql
  encoding: utf8
  host:     <%= ENV.fetch "DB_HOST" %>
  port:     <%= ENV.fetch "DB_PORT" %>
  password: <%= ENV.fetch "DB_PASSWORD" %>
  username: <%= ENV.fetch "DB_USERNAME" %>
  pool:     <%= ENV.fetch "DB_POOL", 5 %>

database_name: &database_name
  database: <%= ENV.fetch "DB_NAME" %>_<%= ENV.fetch "RAILS_ENV" %>

schema_search_path: &schema_search_path
  schema_search_path: "public"

test:
  <<: *default
  <<: *database_name

development:
  <<: *default
  <<: *database_name
  <<: *schema_search_path

production:
  <<: *default
  <<: *database_name
  <<: *schema_search_path
