default: &default
  adapter:  postgresql
  encoding: utf8
  host:     <%= ENV.fetch "DB_HOST" %>
  port:     <%= ENV.fetch "DB_PORT" %>
  password: <%= ENV.fetch "DB_PASSWORD" %>
  username: <%= ENV.fetch "DB_USERNAME" %>
  pool:     <%= ENV.fetch "DB_POOL", 5 %>

test:
  <<: *default
  database: <%= ENV.fetch "DB_NAME" %>_test

development_database_name: &development_database_name
  database: <%= ENV.fetch "DB_NAME" %>_development

schema_search_path: &schema_search_path
  schema_search_path: "public,users"

development:
  <<: *default
  <<: *development_database_name
  <<: *schema_search_path

users_schema:
  <<: *default
  <<: *development_database_name
  schema_search_path: "users"

production:
  <<: *default
  <<: *schema_search_path
  database: <%= ENV.fetch "DB_NAME" %>
