default: &default
  adapter:  postgresql
  encoding: utf8
  host:     <%= ENV.fetch "DB_HOST" %>
  port:     <%= ENV.fetch "DB_PORT" %>
  password: <%= ENV.fetch "DB_PASSWORD" %>
  username: <%= ENV.fetch "DB_USERNAME" %>
  pool:     <%= ENV.fetch "DB_POOL", 5 %>

database_name: &database_name
  database: <%= ENV.fetch "DB_NAME" %>_development

development:
  <<: *default
  <<: *database_name
  schema_search_path: "public,users"

users_schema:
  <<: *default
  <<: *database_name
  schema_search_path: "users"

test:
  <<: *default
  database: <%= ENV.fetch "DB_NAME" %>_test
